### ISSUE TITLE
Add tests for SimpleModelLinter class

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#29]

**Comment by P-Mefut** [comment]
Hi @DhanshreeA, thanks for merging my last PR, can i be assigned to this new issue?!

**Comment by DhanshreeA** [comment]
@P-Mefut please go ahead!

**Comment by P-Mefut** [comment]
Hi @DhanshreeA please I'll like some clarity here about the linter.py file specifically to the SimpleModelLinter class... I see it's trying to verify valid ersilia models and requesting for metadata files which I haven't come across while checking for models like the eos2r5a


Please I'll love some real clarity on how to go about it because I've written the test but now I'm finding difficulty actually testing it over the eos repo which is created during ersilia installation

**Comment by DhanshreeA** [comment]
Hi @P-Mefut that's a good point, this is a new functionality to pack models that we have recently incorporated in Ersilia. A good example of the model structure is for example, [this](https://github.com/ersilia-os/eos3ujl) model repo. You can base off your test fixtures on this one. Hope this helps!

**Comment by P-Mefut** [comment]
Thanks very much @DhanshreeA it'll be of much help

**Comment by DhanshreeA** [comment]
@P-Mefut Actually, my bad, I think we also had a fixture unit testing repository just for this purpose. I am linking it [here](https://github.com/ersilia-os/eos30d7).

**Comment by P-Mefut** [comment]
Thanks @DhanshreeA , Yes that's the one matching the test...

**Comment by P-Mefut** [comment]
Hi @DhanshreeA thanks for merging PR #36 which resolves this issue🙌🤎
